# Properties active for ALL profiles:
---
spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
jwt:
  secret: vijayray
  get:
    token:
      uri: /authenticate